#!/usr/bin/env node
// Builds platform outputs from assets/tokens/tokens.json (the single source of truth).
//   node skills/rdl-theme/scripts/build_tokens.mjs
// Outputs:
//   assets/tokens/tokens.css          CSS custom properties: light/dark × style (glass|flat) × accent packs, auras, type classes
//   assets/tokens/tailwind.preset.js  Tailwind preset wired to the CSS variables
//   assets/ios/RDLTokens.swift        SwiftUI tokens (dynamic light/dark colors, accents, auras, type, space, radius, motion)
// Attributes (put them on <html>): data-theme="light|dark", data-style="glass|flat", data-accent="<pack>".
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const t = JSON.parse(readFileSync(join(root, "assets/tokens/tokens.json"), "utf8"));
const header = (c) => `${c} GENERATED by scripts/build_tokens.mjs from tokens.json — do not edit by hand.\n`;
const DEFAULT_ACCENT = "volt";
const entries = (o) => Object.entries(o).filter(([k]) => !k.startsWith("_"));

// ---------- helpers ----------
const resolve = (v) =>
  typeof v === "string" && v.startsWith("{")
    ? (() => {
        const [fam, step] = v.slice(1, -1).split(".");
        const out = t.primitive[fam]?.[step];
        if (!out) throw new Error(`Unresolved token reference ${v}`);
        return out;
      })()
    : v;
const cssRef = (v) =>
  typeof v === "string" && v.startsWith("{") ? `var(--rdl-${v.slice(1, -1).replace(".", "-")})` : v;
const camel = (s) => s.replace(/[-.](\w)/g, (_, c) => c.toUpperCase()).replace(/^(\d)/, "_$1");
const px = (n) => `${n}px`;

function rgba(value) {
  const v = resolve(value);
  if (v.startsWith("#")) {
    const h = v.slice(1);
    return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255).concat(1);
  }
  const m = v.match(/rgba?\(([^)]+)\)/);
  if (!m) throw new Error(`Cannot parse color ${v}`);
  const [r, g, b, a = "1"] = m[1].split(",").map((s) => s.trim());
  return [r / 255, g / 255, b / 255, Number(a)];
}
function rgbaWithAlpha(v, a) {
  const [r, g, b] = rgba(v);
  return `rgba(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)},${a})`;
}
const swiftArgs = (v) => rgba(v).map((n) => +n.toFixed(4)).join(", ").replace(/^([^,]+), ([^,]+), ([^,]+), (.+)$/, "rdlR: $1, g: $2, b: $3, a: $4");
const tuple = (v) => `(${rgba(v).map((n) => +n.toFixed(4)).join(", ")})`;

const auraCSS = (a) => {
  const stops = a.stops.map(([c, p]) => `${c} ${Math.round(p * 100)}%`).join(", ");
  return a.type === "radial" ? `radial-gradient(120% 110% at ${a.at}, ${stops})` : `linear-gradient(${a.angle}deg, ${stops})`;
};

// ---------- CSS ----------
{
  const L = [header("/*").trim() + " */", ""];
  const acc = t.accents[DEFAULT_ACCENT];
  const accentDark = (p) => [`  --rdl-accent-text: ${cssRef(p["accent-text-dark"])};`, `  --rdl-accent-soft: ${rgbaWithAlpha(p.accent, 0.16)};`];
  const block = (sel, lines) => [`${sel} {`, ...lines, "}", ""];
  const semantic = (o) => entries(o).map(([k, v]) => `  --rdl-${k}: ${cssRef(v)};`);

  const base = [];
  for (const [fam, steps] of entries(t.primitive)) for (const [step, hex] of entries(steps)) base.push(`  --rdl-${fam}-${step}: ${hex};`);
  base.push("", ...semantic(t.semantic.light), "");
  for (const [k, v] of entries(acc)) if (k !== "accent-text-dark") base.push(`  --rdl-${k}: ${cssRef(v)};`);
  base.push("");
  for (const [k, v] of entries(t.type.family)) base.push(`  --rdl-font-${k}: ${v};`);
  base.push(`  --rdl-num-weight: ${t.type.scale.display.weight};`, `  --rdl-display-weight: ${t.type.scale["display-xl"].weight};`);
  base.push(`  --rdl-unit-scale: ${t.type.numerals["unit-scale"]};`);
  for (const [k, v] of entries(t.space)) base.push(`  --rdl-space-${String(k).replace(".", "_")}: ${px(v)};`);
  for (const [k, v] of entries(t.layout)) base.push(`  --rdl-${k}: ${px(v)};`);
  for (const [k, v] of entries(t.radius)) base.push(`  --rdl-radius-${k}: ${px(v)};`);
  base.push(`  --rdl-radius-card: ${px(t.radius.xl)};`, `  --rdl-radius-widget: ${px(t.radius["3xl"])};`);
  for (const [k, v] of entries(t.size)) base.push(`  --rdl-size-${k}: ${px(v)};`);
  for (const [k, v] of entries(t.shadow)) base.push(`  --rdl-shadow-${k}: ${v};`);
  for (const [k, v] of entries(t.motion.duration)) base.push(`  --rdl-duration-${k}: ${v}ms;`);
  for (const [k, v] of entries(t.motion.easing)) base.push(`  --rdl-ease-${k}: ${v};`);
  base.push(`  --rdl-glass-blur: ${px(t.glass.blur)};`, `  --rdl-glass-saturate: ${t.glass.saturate};`);
  base.push(`  --rdl-glass-edge: ${t.glass.edge};`, `  --rdl-glass-iridescent: ${t.glass.iridescent};`);
  for (const [k, a] of entries(t.aura)) base.push(`  --rdl-aura-${k}: ${auraCSS(a)};`);
  base.push("  color-scheme: light;");
  L.push(...block(":root", base));

  const dark = [...semantic(t.semantic.dark), ...accentDark(acc), "  color-scheme: dark;"];
  L.push(...block('[data-theme="dark"]', dark));
  L.push('@media (prefers-color-scheme: dark) {', ...block(':root:not([data-theme="light"])', dark).map((l) => "  " + l), "}", "");

  // Flat style (v1 look). Specificity: [data-style] (0,1,0) and its dark variant (0,2,0) beat the theme blocks above.
  const flat = t.styles.flat;
  const flatVars = entries(flat.vars).map(([k, v]) => `  --rdl-${k}: ${v};`);
  L.push("/* data-style=\"flat\": v1 look — solid cards, Inter, medium numerals, smaller radii, no blur */");
  L.push(...block('[data-style="flat"]', [...semantic(flat.light), ...flatVars]));
  L.push(...block('[data-style="flat"][data-theme="dark"]', semantic(flat.dark)));
  L.push('@media (prefers-color-scheme: dark) {', ...block(':root[data-style="flat"]:not([data-theme="light"])', semantic(flat.dark)).map((l) => "  " + l), "}", "");

  for (const [name, pack] of entries(t.accents)) {
    L.push(`[data-accent="${name}"] {`);
    for (const [k, v] of entries(pack)) if (k !== "accent-text-dark") L.push(`  --rdl-${k}: ${cssRef(v)};`);
    L.push("}");
    L.push(`[data-theme="dark"][data-accent="${name}"] {`, ...accentDark(pack), "}");
    L.push(`@media (prefers-color-scheme: dark) { :root:not([data-theme="light"])[data-accent="${name}"] {`, ...accentDark(pack).map((l) => "  " + l), "} }");
  }
  L.push("");
  L.push("/* Type roles — use on any element: <p class=\"rdl-h1\">. Display roles follow --rdl-num-weight (300 glass / 500 flat). */");
  for (const [k, s] of entries(t.type.scale)) {
    const weight = ["display-xl", "display", "numeral"].includes(k) ? "var(--rdl-num-weight)" : s.weight;
    L.push(`.rdl-${k} { font-family: var(--rdl-font-sans); font-size: ${px(s.size)}; line-height: ${px(s.line)}; font-weight: ${weight}; letter-spacing: ${s.tracking}em; }`);
  }
  L.push(".rdl-num { font-variant-numeric: tabular-nums; font-feature-settings: \"tnum\" 1; }");
  L.push(".rdl-dot { font-family: var(--rdl-font-dot); font-weight: 700; letter-spacing: 0; }");
  writeFileSync(join(root, "assets/tokens/tokens.css"), L.join("\n") + "\n");
}

// ---------- Tailwind preset ----------
{
  const v = (k) => `var(--rdl-${k})`;
  const colors = {};
  for (const [fam, steps] of entries(t.primitive)) {
    colors[fam] = {};
    for (const step of Object.keys(steps)) colors[fam][step] = v(`${fam}-${step}`);
  }
  for (const k of Object.keys(t.semantic.light)) colors[k] = v(k);
  for (const k of Object.keys(t.accents[DEFAULT_ACCENT])) if (k !== "accent-text-dark") colors[k] = v(k);
  const fontSize = Object.fromEntries(
    entries(t.type.scale).map(([k, s]) => [k, [px(s.size), { lineHeight: px(s.line), letterSpacing: `${s.tracking}em`, fontWeight: String(s.weight) }]])
  );
  const preset = {
    theme: {
      extend: {
        colors,
        fontFamily: { sans: [v("font-sans")], dot: [v("font-dot")], flat: [v("font-flat")], mono: [v("font-mono")] },
        fontSize,
        spacing: Object.fromEntries(entries(t.layout).map(([k, n]) => [k, px(n)])),
        borderRadius: {
          ...Object.fromEntries(entries(t.radius).map(([k, n]) => [k === "pill" ? "pill" : `rdl-${k}`, px(n)])),
          card: v("radius-card"),
          widget: v("radius-widget"),
        },
        boxShadow: Object.fromEntries(entries(t.shadow).map(([k, s]) => [`rdl-${k}`, s])),
        backgroundImage: Object.fromEntries(entries(t.aura).map(([k]) => [`aura-${k}`, v(`aura-${k}`)])),
        backdropBlur: { glass: v("glass-blur") },
        transitionTimingFunction: Object.fromEntries(entries(t.motion.easing).map(([k, e]) => [`rdl-${k}`, e])),
        transitionDuration: Object.fromEntries(entries(t.motion.duration).map(([k, d]) => [`rdl-${k}`, `${d}ms`])),
      },
    },
  };
  writeFileSync(
    join(root, "assets/tokens/tailwind.preset.js"),
    header("//") + "// Import tokens.css once globally, then: presets: [require('./tailwind.preset.js')]\n" +
      "module.exports = " + JSON.stringify(preset, null, 2) + ";\n"
  );
}

// ---------- SwiftUI ----------
{
  const S = [header("//"), "import SwiftUI", "#if canImport(UIKit)", "import UIKit", "#endif", ""];
  S.push("// MARK: - Color", "");
  S.push("public extension Color {");
  S.push("    init(rdlR r: Double, g: Double, b: Double, a: Double = 1) { self.init(.sRGB, red: r, green: g, blue: b, opacity: a) }");
  S.push("");
  S.push("    /// Resolves to `light` or `dark` depending on the current color scheme.");
  S.push("    static func rdlDynamic(light: (Double, Double, Double, Double), dark: (Double, Double, Double, Double)) -> Color {");
  S.push("        #if canImport(UIKit)");
  S.push("        return Color(UIColor { traits in");
  S.push("            let c = traits.userInterfaceStyle == .dark ? dark : light");
  S.push("            return UIColor(red: c.0, green: c.1, blue: c.2, alpha: c.3)");
  S.push("        })");
  S.push("        #else");
  S.push("        return Color(.sRGB, red: light.0, green: light.1, blue: light.2, opacity: light.3)");
  S.push("        #endif");
  S.push("    }");
  S.push("}", "");

  S.push("/// Raw palette. Prefer `RDLColor` semantic roles in UI code.");
  S.push("public enum RDLPalette {");
  for (const [fam, steps] of entries(t.primitive))
    for (const [step, hex] of entries(steps)) S.push(`    public static let ${fam}${step} = Color(${swiftArgs(hex)})`);
  S.push("}", "");

  S.push("/// Semantic roles — adapt to light/dark automatically.");
  S.push("public enum RDLColor {");
  for (const k of Object.keys(t.semantic.light))
    S.push(`    public static let ${camel(k)} = Color.rdlDynamic(light: ${tuple(t.semantic.light[k])}, dark: ${tuple(t.semantic.dark[k])})`);
  S.push("}", "");

  S.push("/// Accent pack. Pick one per product and inject with `.rdlAccent(.volt)`.");
  S.push("public struct RDLAccent {");
  S.push("    public let accent: Color, accentStrong: Color, accentSoft: Color, onAccent: Color, accentText: Color");
  for (const [name, p] of entries(t.accents)) {
    S.push(
      `    public static let ${name} = RDLAccent(accent: Color(${swiftArgs(p.accent)}), ` +
        `accentStrong: Color(${swiftArgs(p["accent-strong"])}), ` +
        `accentSoft: Color.rdlDynamic(light: ${tuple(p["accent-soft"])}, dark: ${tuple(rgbaWithAlpha(p.accent, 0.16))}), ` +
        `onAccent: Color(${swiftArgs(p["on-accent"])}), ` +
        `accentText: Color.rdlDynamic(light: ${tuple(p["accent-text"])}, dark: ${tuple(p["accent-text-dark"])}))`
    );
  }
  S.push("}", "");
  S.push(`private struct RDLAccentKey: EnvironmentKey { static let defaultValue = RDLAccent.${DEFAULT_ACCENT} }`);
  S.push("public extension EnvironmentValues {");
  S.push("    var rdlAccent: RDLAccent { get { self[RDLAccentKey.self] } set { self[RDLAccentKey.self] = newValue } }");
  S.push("}");
  S.push("public extension View {");
  S.push("    func rdlAccent(_ accent: RDLAccent) -> some View { environment(\\.rdlAccent, accent) }");
  S.push("}", "");

  S.push("// MARK: - Aura gradients", "");
  S.push("/// Soft gradient washes for card fills and screen backdrops.");
  S.push("public enum RDLAura {");
  for (const [k, a] of entries(t.aura)) {
    const stops = a.stops.map(([c, p]) => `.init(color: Color(${swiftArgs(c)}), location: ${p})`).join(", ");
    if (a.type === "radial") {
      const [x, y] = a.at.split(" ").map((s) => parseFloat(s) / 100);
      S.push(`    public static let ${k} = RadialGradient(stops: [${stops}], center: UnitPoint(x: ${x}, y: ${y}), startRadius: 0, endRadius: 520)`);
    } else {
      const r = (a.angle * Math.PI) / 180;
      const f = (n) => +n.toFixed(3);
      const start = `UnitPoint(x: ${f(0.5 - Math.sin(r) / 2)}, y: ${f(0.5 + Math.cos(r) / 2)})`;
      const end = `UnitPoint(x: ${f(0.5 + Math.sin(r) / 2)}, y: ${f(0.5 - Math.cos(r) / 2)})`;
      S.push(`    public static let ${k} = LinearGradient(stops: [${stops}], startPoint: ${start}, endPoint: ${end})`);
    }
  }
  S.push("}", "");

  S.push("// MARK: - Type", "");
  S.push("/// Set `RDLFont.family` to a bundled font name (e.g. \"Urbanist\") to match the web; nil uses the system font.");
  S.push("public enum RDLFont {");
  S.push("    public static var family: String? = \"Urbanist\"");
  S.push("}");
  S.push("public struct RDLTextStyle {");
  S.push("    public let size: CGFloat, lineHeight: CGFloat, weight: Font.Weight, tracking: CGFloat");
  S.push("    public var font: Font {");
  S.push("        #if canImport(UIKit)");
  S.push("        if let family = RDLFont.family, UIFont(name: family, size: size) != nil {");
  S.push("            return .custom(family, size: size).weight(weight)");
  S.push("        }");
  S.push("        #endif");
  S.push("        return .system(size: size, weight: weight, design: .default)");
  S.push("    }");
  S.push("}");
  const w = { 300: ".light", 400: ".regular", 500: ".medium", 600: ".semibold", 700: ".bold" };
  S.push("public enum RDLType {");
  for (const [k, s] of entries(t.type.scale))
    S.push(`    public static let ${camel(k)} = RDLTextStyle(size: ${s.size}, lineHeight: ${s.line}, weight: ${w[s.weight]}, tracking: ${+(s.tracking * s.size).toFixed(2)})`);
  S.push(`    /// Units next to numbers render at this fraction of the number size.`);
  S.push(`    public static let unitScale: CGFloat = ${t.type.numerals["unit-scale"]}`);
  S.push("}");
  S.push("public extension View {");
  S.push("    /// Applies an RDL type role: size, weight, tracking and line height.");
  S.push("    func rdlType(_ style: RDLTextStyle) -> some View {");
  S.push("        font(style.font)");
  S.push("            .tracking(style.tracking)");
  S.push("            .lineSpacing(max(0, style.lineHeight - style.size * 1.2))");
  S.push("    }");
  S.push("}", "");

  S.push("// MARK: - Space, radius, size, glass, motion", "");
  S.push("public enum RDLSpace {");
  for (const [k, n] of entries(t.space)) S.push(`    public static let s${String(k).replace(".", "_")}: CGFloat = ${n}`);
  for (const [k, n] of entries(t.layout)) S.push(`    public static let ${camel(k)}: CGFloat = ${n}`);
  S.push("}");
  S.push("public enum RDLRadius {");
  const swiftRadius = { "2xl": "xxl", "3xl": "xxxl" };
  for (const [k, n] of entries(t.radius)) S.push(`    public static let ${swiftRadius[k] ?? camel(k)}: CGFloat = ${n}`);
  S.push(`    public static let card: CGFloat = ${t.radius.xl}`);
  S.push(`    public static let widget: CGFloat = ${t.radius["3xl"]}`);
  S.push("}");
  S.push("public enum RDLSize {");
  for (const [k, n] of entries(t.size)) S.push(`    public static let ${camel(k)}: CGFloat = ${n}`);
  S.push("}");
  S.push("public enum RDLGlass {");
  S.push(`    public static let blur: CGFloat = ${t.glass.blur}`);
  S.push("}");
  S.push("public enum RDLMotion {");
  for (const [k, n] of entries(t.motion.duration)) S.push(`    public static let ${k}: Double = ${n / 1000}`);
  S.push(`    public static let spring = Animation.spring(response: ${t.motion.spring.response}, dampingFraction: ${t.motion.spring.damping})`);
  S.push(`    public static let standard = Animation.timingCurve(0.2, 0, 0, 1, duration: ${t.motion.duration.base / 1000})`);
  S.push(`    public static let stagger: Double = ${t.motion.stagger / 1000}`);
  S.push("}");
  writeFileSync(join(root, "assets/ios/RDLTokens.swift"), S.join("\n") + "\n");
}

console.log("Built tokens.css, tailwind.preset.js, RDLTokens.swift");
