#!/usr/bin/env node
// Builds platform outputs from assets/tokens/tokens.json (the single source of truth).
//   node skills/rdl-theme/scripts/build_tokens.mjs
// Outputs:
//   assets/tokens/tokens.css          CSS custom properties (light, dark, accent packs) + type classes
//   assets/tokens/tailwind.preset.js  Tailwind preset wired to the CSS variables
//   assets/ios/RDLTokens.swift        SwiftUI tokens (dynamic light/dark colors, type, space, radius)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const t = JSON.parse(readFileSync(join(root, "assets/tokens/tokens.json"), "utf8"));
const header = (c) => `${c} GENERATED by scripts/build_tokens.mjs from tokens.json — do not edit by hand.\n`;

// ---------- helpers ----------
const resolve = (v) =>
  typeof v === "string" && v.startsWith("{")
    ? (() => {
        const [fam, step] = v.slice(1, -1).split(".");
        const out = t.primitive[fam]?.[step];
        if (!out) throw new Error(`Unresolved token reference ${v}`);
        return out;
      })()
    : v;
const cssRef = (v) =>
  typeof v === "string" && v.startsWith("{") ? `var(--rdl-${v.slice(1, -1).replace(".", "-")})` : v;
const camel = (s) => s.replace(/[-.](\w)/g, (_, c) => c.toUpperCase()).replace(/^(\d)/, "_$1");
const px = (n) => `${n}px`;

function rgba(value) {
  const v = resolve(value);
  if (v.startsWith("#")) {
    const h = v.slice(1);
    return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255).concat(1);
  }
  const m = v.match(/rgba?\(([^)]+)\)/);
  if (!m) throw new Error(`Cannot parse color ${v}`);
  const [r, g, b, a = "1"] = m[1].split(",").map((s) => s.trim());
  return [r / 255, g / 255, b / 255, Number(a)];
}
const swiftRGBA = (v) => {
  const [r, g, b, a] = rgba(v).map((n) => +n.toFixed(4));
  return `r: ${r}, g: ${g}, b: ${b}, a: ${a}`;
};

// ---------- CSS ----------
{
  const L = [header("/*").trim() + " */", ""];
  L.push(":root {");
  for (const [fam, steps] of Object.entries(t.primitive))
    for (const [step, hex] of Object.entries(steps)) L.push(`  --rdl-${fam}-${step}: ${hex};`);
  L.push("");
  for (const [k, v] of Object.entries(t.semantic.light)) L.push(`  --rdl-${k}: ${cssRef(v)};`);
  L.push("");
  const lime = t.accents.lime;
  for (const [k, v] of Object.entries(lime)) if (k !== "accent-text-dark") L.push(`  --rdl-${k}: ${cssRef(v)};`);
  L.push("");
  for (const [k, v] of Object.entries(t.type.family)) L.push(`  --rdl-font-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.space)) L.push(`  --rdl-space-${String(k).replace(".", "_")}: ${px(v)};`);
  for (const [k, v] of Object.entries(t.layout)) L.push(`  --rdl-${k}: ${px(v)};`);
  for (const [k, v] of Object.entries(t.radius)) L.push(`  --rdl-radius-${k}: ${px(v)};`);
  for (const [k, v] of Object.entries(t.size)) L.push(`  --rdl-size-${k}: ${px(v)};`);
  for (const [k, v] of Object.entries(t.shadow)) L.push(`  --rdl-shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.motion.duration)) L.push(`  --rdl-duration-${k}: ${v}ms;`);
  for (const [k, v] of Object.entries(t.motion.easing)) L.push(`  --rdl-ease-${k}: ${v};`);
  L.push("  color-scheme: light;");
  L.push("}", "");

  // Accent packs: light values on [data-accent], dark overrides (text + soft tint) at higher specificity.
  // Put data-theme and data-accent on <html>.
  const accentDark = (p) => [
    `  --rdl-accent-text: ${cssRef(p["accent-text-dark"])};`,
    `  --rdl-accent-soft: ${rgbaWithAlpha(p.accent, 0.16)};`,
  ];
  const dark = Object.entries(t.semantic.dark).map(([k, v]) => `  --rdl-${k}: ${cssRef(v)};`);
  L.push("[data-theme=\"dark\"] {", ...dark, ...accentDark(t.accents.lime), "  color-scheme: dark;", "}", "");
  L.push("@media (prefers-color-scheme: dark) {", "  :root:not([data-theme=\"light\"]) {");
  L.push(...dark.map((l) => "  " + l), ...accentDark(t.accents.lime).map((l) => "  " + l), "    color-scheme: dark;", "  }", "}", "");

  for (const [name, pack] of Object.entries(t.accents)) {
    L.push(`[data-accent="${name}"] {`);
    for (const [k, v] of Object.entries(pack)) if (k !== "accent-text-dark") L.push(`  --rdl-${k}: ${cssRef(v)};`);
    L.push("}");
    L.push(`[data-theme="dark"][data-accent="${name}"] {`, ...accentDark(pack), "}");
    L.push(`@media (prefers-color-scheme: dark) { :root:not([data-theme="light"])[data-accent="${name}"] {`, ...accentDark(pack).map((l) => "  " + l), "} }");
  }
  L.push("");
  L.push("/* Type roles — use on any element: <p class=\"rdl-h1\"> */");
  for (const [k, s] of Object.entries(t.type.scale)) {
    L.push(
      `.rdl-${k} { font-family: var(--rdl-font-sans); font-size: ${px(s.size)}; line-height: ${px(s.line)}; font-weight: ${s.weight}; letter-spacing: ${s.tracking}em; }`
    );
  }
  L.push(".rdl-num { font-variant-numeric: tabular-nums; font-feature-settings: \"tnum\" 1, \"cv11\" 1; }");
  writeFileSync(join(root, "assets/tokens/tokens.css"), L.join("\n") + "\n");
}

// ---------- Tailwind preset ----------
{
  const v = (k) => `var(--rdl-${k})`;
  const colors = {};
  for (const [fam, steps] of Object.entries(t.primitive)) {
    colors[fam] = {};
    for (const step of Object.keys(steps)) colors[fam][step] = v(`${fam}-${step}`);
  }
  for (const k of Object.keys(t.semantic.light)) colors[k] = v(k);
  for (const k of Object.keys(t.accents.lime)) if (k !== "accent-text-dark") colors[k] = v(k);
  const fontSize = Object.fromEntries(
    Object.entries(t.type.scale).map(([k, s]) => [
      k,
      [px(s.size), { lineHeight: px(s.line), letterSpacing: `${s.tracking}em`, fontWeight: String(s.weight) }],
    ])
  );
  const preset = {
    theme: {
      extend: {
        colors,
        fontFamily: { sans: [v("font-sans")], alt: [v("font-sans-alt")], mono: [v("font-mono")] },
        fontSize,
        spacing: Object.fromEntries(Object.entries(t.layout).map(([k, n]) => [k, px(n)])),
        borderRadius: Object.fromEntries(Object.entries(t.radius).map(([k, n]) => [k === "pill" ? "pill" : `rdl-${k}`, px(n)])),
        boxShadow: Object.fromEntries(Object.entries(t.shadow).map(([k, s]) => [`rdl-${k}`, s])),
        transitionTimingFunction: Object.fromEntries(Object.entries(t.motion.easing).map(([k, e]) => [`rdl-${k}`, e])),
        transitionDuration: Object.fromEntries(Object.entries(t.motion.duration).map(([k, d]) => [`rdl-${k}`, `${d}ms`])),
      },
    },
  };
  writeFileSync(
    join(root, "assets/tokens/tailwind.preset.js"),
    header("//") + "// Import tokens.css once globally, then: presets: [require('./tailwind.preset.js')]\n" +
      "module.exports = " + JSON.stringify(preset, null, 2) + ";\n"
  );
}

// ---------- SwiftUI ----------
{
  const S = [header("//"), "import SwiftUI", "#if canImport(UIKit)", "import UIKit", "#endif", ""];
  S.push("// MARK: - Color", "");
  S.push("public extension Color {");
  S.push("    init(rdlR r: Double, g: Double, b: Double, a: Double = 1) { self.init(.sRGB, red: r, green: g, blue: b, opacity: a) }");
  S.push("");
  S.push("    /// Resolves to `light` or `dark` depending on the current color scheme.");
  S.push("    static func rdlDynamic(light: (Double, Double, Double, Double), dark: (Double, Double, Double, Double)) -> Color {");
  S.push("        #if canImport(UIKit)");
  S.push("        return Color(UIColor { traits in");
  S.push("            let c = traits.userInterfaceStyle == .dark ? dark : light");
  S.push("            return UIColor(red: c.0, green: c.1, blue: c.2, alpha: c.3)");
  S.push("        })");
  S.push("        #else");
  S.push("        return Color(.sRGB, red: light.0, green: light.1, blue: light.2, opacity: light.3)");
  S.push("        #endif");
  S.push("    }");
  S.push("}", "");

  S.push("/// Raw palette. Prefer `RDLColor` semantic roles in UI code.");
  S.push("public enum RDLPalette {");
  for (const [fam, steps] of Object.entries(t.primitive))
    for (const [step, hex] of Object.entries(steps))
      S.push(`    public static let ${fam}${step} = Color(rdlR: ${swiftRGBA(hex).replace("r: ", "")})`);
  S.push("}", "");

  const tuple = (v) => `(${rgba(v).map((n) => +n.toFixed(4)).join(", ")})`;
  S.push("/// Semantic roles — adapt to light/dark automatically.");
  S.push("public enum RDLColor {");
  for (const k of Object.keys(t.semantic.light))
    S.push(`    public static let ${camel(k)} = Color.rdlDynamic(light: ${tuple(t.semantic.light[k])}, dark: ${tuple(t.semantic.dark[k])})`);
  S.push("}", "");

  S.push("/// Accent pack. Pick one per product and inject with `.rdlAccent(.lime)`.");
  S.push("public struct RDLAccent {");
  S.push("    public let accent: Color, accentStrong: Color, accentSoft: Color, onAccent: Color, accentText: Color");
  for (const [name, p] of Object.entries(t.accents)) {
    S.push(
      `    public static let ${name} = RDLAccent(accent: Color(rdlR: ${swiftRGBA(p.accent).replace("r: ", "")}), ` +
        `accentStrong: Color(rdlR: ${swiftRGBA(p["accent-strong"]).replace("r: ", "")}), ` +
        `accentSoft: Color.rdlDynamic(light: ${tuple(p["accent-soft"])}, dark: ${tuple(rgbaWithAlpha(p.accent, 0.16))}), ` +
        `onAccent: Color(rdlR: ${swiftRGBA(p["on-accent"]).replace("r: ", "")}), ` +
        `accentText: Color.rdlDynamic(light: ${tuple(p["accent-text"])}, dark: ${tuple(p["accent-text-dark"])}))`
    );
  }
  S.push("}", "");
  S.push("private struct RDLAccentKey: EnvironmentKey { static let defaultValue = RDLAccent.lime }");
  S.push("public extension EnvironmentValues {");
  S.push("    var rdlAccent: RDLAccent { get { self[RDLAccentKey.self] } set { self[RDLAccentKey.self] = newValue } }");
  S.push("}");
  S.push("public extension View {");
  S.push("    func rdlAccent(_ accent: RDLAccent) -> some View { environment(\\.rdlAccent, accent) }");
  S.push("}", "");

  S.push("// MARK: - Type", "");
  S.push("public struct RDLTextStyle {");
  S.push("    public let size: CGFloat, lineHeight: CGFloat, weight: Font.Weight, tracking: CGFloat");
  S.push("    public var font: Font { .system(size: size, weight: weight, design: .default) }");
  S.push("}");
  const w = { 400: ".regular", 500: ".medium", 600: ".semibold", 700: ".bold" };
  S.push("public enum RDLType {");
  for (const [k, s] of Object.entries(t.type.scale))
    S.push(`    public static let ${camel(k)} = RDLTextStyle(size: ${s.size}, lineHeight: ${s.line}, weight: ${w[s.weight]}, tracking: ${+(s.tracking * s.size).toFixed(2)})`);
  S.push("}");
  S.push("public extension View {");
  S.push("    /// Applies an RDL type role: size, weight, tracking and line height.");
  S.push("    func rdlType(_ style: RDLTextStyle) -> some View {");
  S.push("        font(style.font)");
  S.push("            .tracking(style.tracking)");
  S.push("            .lineSpacing(max(0, style.lineHeight - style.size * 1.2))");
  S.push("    }");
  S.push("}", "");

  S.push("// MARK: - Space, radius, size, motion", "");
  S.push("public enum RDLSpace {");
  for (const [k, n] of Object.entries(t.space)) S.push(`    public static let s${String(k).replace(".", "_")}: CGFloat = ${n}`);
  for (const [k, n] of Object.entries(t.layout)) S.push(`    public static let ${camel(k)}: CGFloat = ${n}`);
  S.push("}");
  S.push("public enum RDLRadius {");
  const swiftRadius = { "2xl": "xxl", "3xl": "xxxl" };
  for (const [k, n] of Object.entries(t.radius)) S.push(`    public static let ${swiftRadius[k] ?? camel(k)}: CGFloat = ${n}`);
  S.push("}");
  S.push("public enum RDLSize {");
  for (const [k, n] of Object.entries(t.size)) S.push(`    public static let ${camel(k)}: CGFloat = ${n}`);
  S.push("}");
  S.push("public enum RDLMotion {");
  for (const [k, n] of Object.entries(t.motion.duration)) S.push(`    public static let ${k}: Double = ${n / 1000}`);
  S.push(`    public static let spring = Animation.spring(response: ${t.motion.spring.response}, dampingFraction: ${t.motion.spring.damping})`);
  S.push(`    public static let standard = Animation.timingCurve(0.2, 0, 0, 1, duration: ${t.motion.duration.base / 1000})`);
  S.push(`    public static let stagger: Double = ${t.motion.stagger / 1000}`);
  S.push("}");
  writeFileSync(join(root, "assets/ios/RDLTokens.swift"), S.join("\n") + "\n");
}

function rgbaWithAlpha(v, a) {
  const [r, g, b] = rgba(v);
  return `rgba(${Math.round(r * 255)},${Math.round(g * 255)},${Math.round(b * 255)},${a})`;
}

console.log("Built tokens.css, tailwind.preset.js, RDLTokens.swift");
