// GENERATED by scripts/build_tokens.mjs from tokens.json — do not edit by hand.

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Color

public extension Color {
    init(rdlR r: Double, g: Double, b: Double, a: Double = 1) { self.init(.sRGB, red: r, green: g, blue: b, opacity: a) }

    /// Resolves to `light` or `dark` depending on the current color scheme.
    static func rdlDynamic(light: (Double, Double, Double, Double), dark: (Double, Double, Double, Double)) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { traits in
            let c = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: c.0, green: c.1, blue: c.2, alpha: c.3)
        })
        #else
        return Color(.sRGB, red: light.0, green: light.1, blue: light.2, opacity: light.3)
        #endif
    }
}

/// Raw palette. Prefer `RDLColor` semantic roles in UI code.
public enum RDLPalette {
    public static let ink600 = Color(rdlR: 0.2039, g: 0.2039, b: 0.2275, a: 1)
    public static let ink700 = Color(rdlR: 0.149, g: 0.149, b: 0.1686, a: 1)
    public static let ink800 = Color(rdlR: 0.1098, g: 0.1098, b: 0.1255, a: 1)
    public static let ink900 = Color(rdlR: 0.0784, g: 0.0784, b: 0.0902, a: 1)
    public static let ink950 = Color(rdlR: 0.0431, g: 0.0431, b: 0.051, a: 1)
    public static let gray0 = Color(rdlR: 1, g: 1, b: 1, a: 1)
    public static let gray50 = Color(rdlR: 0.9725, g: 0.9725, b: 0.9804, a: 1)
    public static let gray100 = Color(rdlR: 0.9529, g: 0.9529, b: 0.9608, a: 1)
    public static let gray150 = Color(rdlR: 0.9216, g: 0.9216, b: 0.9373, a: 1)
    public static let gray200 = Color(rdlR: 0.8863, g: 0.8863, b: 0.9059, a: 1)
    public static let gray300 = Color(rdlR: 0.7843, g: 0.7843, b: 0.8118, a: 1)
    public static let gray400 = Color(rdlR: 0.6039, g: 0.6039, b: 0.6392, a: 1)
    public static let gray500 = Color(rdlR: 0.4314, g: 0.4314, b: 0.4706, a: 1)
    public static let gray600 = Color(rdlR: 0.3333, g: 0.3333, b: 0.3686, a: 1)
    public static let lime50 = Color(rdlR: 0.9686, g: 0.9922, b: 0.8902, a: 1)
    public static let lime100 = Color(rdlR: 0.9333, g: 0.9843, b: 0.7686, a: 1)
    public static let lime200 = Color(rdlR: 0.8902, g: 0.9725, b: 0.6039, a: 1)
    public static let lime300 = Color(rdlR: 0.8471, g: 0.9608, b: 0.4353, a: 1)
    public static let lime400 = Color(rdlR: 0.7961, g: 0.9373, b: 0.2627, a: 1)
    public static let lime500 = Color(rdlR: 0.698, g: 0.851, b: 0.1647, a: 1)
    public static let lime600 = Color(rdlR: 0.549, g: 0.6863, b: 0.0706, a: 1)
    public static let lime700 = Color(rdlR: 0.3725, g: 0.4784, b: 0.0314, a: 1)
    public static let violet50 = Color(rdlR: 0.9569, g: 0.9451, b: 1, a: 1)
    public static let violet100 = Color(rdlR: 0.9137, g: 0.8902, b: 1, a: 1)
    public static let violet200 = Color(rdlR: 0.8235, g: 0.7765, b: 1, a: 1)
    public static let violet300 = Color(rdlR: 0.6902, g: 0.6118, b: 1, a: 1)
    public static let violet400 = Color(rdlR: 0.5647, g: 0.4627, b: 1, a: 1)
    public static let violet500 = Color(rdlR: 0.4431, g: 0.3216, b: 0.9608, a: 1)
    public static let violet600 = Color(rdlR: 0.3529, g: 0.2314, b: 0.8588, a: 1)
    public static let violet700 = Color(rdlR: 0.2627, g: 0.1608, b: 0.6824, a: 1)
    public static let orange50 = Color(rdlR: 1, g: 0.9529, b: 0.9333, a: 1)
    public static let orange100 = Color(rdlR: 1, g: 0.8902, b: 0.8431, a: 1)
    public static let orange200 = Color(rdlR: 1, g: 0.7647, b: 0.6667, a: 1)
    public static let orange300 = Color(rdlR: 1, g: 0.6157, b: 0.4588, a: 1)
    public static let orange400 = Color(rdlR: 1, g: 0.4784, b: 0.2706, a: 1)
    public static let orange500 = Color(rdlR: 0.9608, g: 0.3725, b: 0.1412, a: 1)
    public static let orange600 = Color(rdlR: 0.8235, g: 0.2824, b: 0.0706, a: 1)
    public static let orange700 = Color(rdlR: 0.6314, g: 0.2118, b: 0.0431, a: 1)
    public static let blue50 = Color(rdlR: 0.9333, g: 0.9569, b: 1, a: 1)
    public static let blue100 = Color(rdlR: 0.8627, g: 0.9059, b: 1, a: 1)
    public static let blue200 = Color(rdlR: 0.7137, g: 0.8, b: 1, a: 1)
    public static let blue300 = Color(rdlR: 0.5176, g: 0.6627, b: 1, a: 1)
    public static let blue400 = Color(rdlR: 0.3333, g: 0.5216, b: 1, a: 1)
    public static let blue500 = Color(rdlR: 0.1843, g: 0.4, b: 0.9647, a: 1)
    public static let blue600 = Color(rdlR: 0.1216, g: 0.3098, b: 0.8196, a: 1)
    public static let blue700 = Color(rdlR: 0.0902, g: 0.2314, b: 0.6196, a: 1)
    public static let gold50 = Color(rdlR: 0.9922, g: 0.9725, b: 0.9176, a: 1)
    public static let gold100 = Color(rdlR: 0.9804, g: 0.9294, b: 0.7804, a: 1)
    public static let gold200 = Color(rdlR: 0.9569, g: 0.8549, b: 0.5569, a: 1)
    public static let gold300 = Color(rdlR: 0.9216, g: 0.7686, b: 0.3608, a: 1)
    public static let gold400 = Color(rdlR: 0.8667, g: 0.6824, b: 0.2275, a: 1)
    public static let gold500 = Color(rdlR: 0.7647, g: 0.5725, b: 0.1333, a: 1)
    public static let gold600 = Color(rdlR: 0.6118, g: 0.4471, b: 0.0824, a: 1)
    public static let gold700 = Color(rdlR: 0.4314, g: 0.3137, b: 0.0549, a: 1)
    public static let mint50 = Color(rdlR: 0.9176, g: 0.9843, b: 0.9529, a: 1)
    public static let mint100 = Color(rdlR: 0.8118, g: 0.9608, b: 0.8902, a: 1)
    public static let mint300 = Color(rdlR: 0.4863, g: 0.8784, b: 0.702, a: 1)
    public static let mint500 = Color(rdlR: 0.1216, g: 0.7216, b: 0.4667, a: 1)
    public static let mint600 = Color(rdlR: 0.0745, g: 0.5882, b: 0.3725, a: 1)
    public static let mint700 = Color(rdlR: 0.0549, g: 0.4392, b: 0.2824, a: 1)
    public static let red50 = Color(rdlR: 1, g: 0.9412, b: 0.9412, a: 1)
    public static let red100 = Color(rdlR: 1, g: 0.8627, b: 0.8627, a: 1)
    public static let red300 = Color(rdlR: 1, g: 0.6039, b: 0.6039, a: 1)
    public static let red500 = Color(rdlR: 0.9412, g: 0.2706, b: 0.2431, a: 1)
    public static let red600 = Color(rdlR: 0.8, g: 0.1843, b: 0.1608, a: 1)
    public static let amber50 = Color(rdlR: 1, g: 0.9725, b: 0.902, a: 1)
    public static let amber100 = Color(rdlR: 1, g: 0.9294, b: 0.749, a: 1)
    public static let amber300 = Color(rdlR: 1, g: 0.8235, b: 0.4, a: 1)
    public static let amber500 = Color(rdlR: 0.9608, g: 0.6549, b: 0.0431, a: 1)
    public static let amber600 = Color(rdlR: 0.8, g: 0.5294, b: 0, a: 1)
    public static let amber700 = Color(rdlR: 0.5412, g: 0.3569, b: 0, a: 1)
}

/// Semantic roles — adapt to light/dark automatically.
public enum RDLColor {
    public static let bgCanvas = Color.rdlDynamic(light: (0.9529, 0.9529, 0.9608, 1), dark: (0.0431, 0.0431, 0.051, 1))
    public static let bgSurface = Color.rdlDynamic(light: (1, 1, 1, 1), dark: (0.0902, 0.0902, 0.102, 1))
    public static let bgSurfaceMuted = Color.rdlDynamic(light: (0.9529, 0.9529, 0.9608, 1), dark: (0.1255, 0.1255, 0.1412, 1))
    public static let bgHero = Color.rdlDynamic(light: (0.0431, 0.0431, 0.051, 1), dark: (0.1373, 0.1373, 0.1529, 1))
    public static let bgHeroRaised = Color.rdlDynamic(light: (0.149, 0.149, 0.1686, 1), dark: (0.2039, 0.2039, 0.2275, 1))
    public static let fillControl = Color.rdlDynamic(light: (0.9529, 0.9529, 0.9608, 1), dark: (0.1373, 0.1373, 0.1529, 1))
    public static let fillControlHover = Color.rdlDynamic(light: (0.9216, 0.9216, 0.9373, 1), dark: (0.1725, 0.1725, 0.1922, 1))
    public static let fillControlStrong = Color.rdlDynamic(light: (0.0431, 0.0431, 0.051, 1), dark: (1, 1, 1, 1))
    public static let textPrimary = Color.rdlDynamic(light: (0.0431, 0.0431, 0.051, 1), dark: (0.9608, 0.9608, 0.9686, 1))
    public static let textSecondary = Color.rdlDynamic(light: (0.4314, 0.4314, 0.4706, 1), dark: (0.6392, 0.6392, 0.6784, 1))
    public static let textTertiary = Color.rdlDynamic(light: (0.6039, 0.6039, 0.6392, 1), dark: (0.4314, 0.4314, 0.4706, 1))
    public static let textOnHero = Color.rdlDynamic(light: (1, 1, 1, 1), dark: (1, 1, 1, 1))
    public static let textOnHeroMuted = Color.rdlDynamic(light: (0.6392, 0.6392, 0.6784, 1), dark: (0.6392, 0.6392, 0.6784, 1))
    public static let textOnStrong = Color.rdlDynamic(light: (1, 1, 1, 1), dark: (0.0431, 0.0431, 0.051, 1))
    public static let borderSubtle = Color.rdlDynamic(light: (0.8863, 0.8863, 0.9059, 1), dark: (0.149, 0.149, 0.1686, 1))
    public static let borderStrong = Color.rdlDynamic(light: (0.7843, 0.7843, 0.8118, 1), dark: (0.2039, 0.2039, 0.2275, 1))
    public static let chartTrack = Color.rdlDynamic(light: (0.9216, 0.9216, 0.9373, 1), dark: (0.1373, 0.1373, 0.1529, 1))
    public static let chartMuted = Color.rdlDynamic(light: (0.8863, 0.8863, 0.9059, 1), dark: (0.1725, 0.1725, 0.1922, 1))
    public static let chartHatch = Color.rdlDynamic(light: (0.7843, 0.7843, 0.8118, 1), dark: (0.2667, 0.2667, 0.2941, 1))
    public static let success = Color.rdlDynamic(light: (0.1216, 0.7216, 0.4667, 1), dark: (0.4863, 0.8784, 0.702, 1))
    public static let successSoft = Color.rdlDynamic(light: (0.9176, 0.9843, 0.9529, 1), dark: (0.1216, 0.7216, 0.4667, 0.14))
    public static let successText = Color.rdlDynamic(light: (0.0549, 0.4392, 0.2824, 1), dark: (0.4863, 0.8784, 0.702, 1))
    public static let danger = Color.rdlDynamic(light: (0.9412, 0.2706, 0.2431, 1), dark: (1, 0.6039, 0.6039, 1))
    public static let dangerSoft = Color.rdlDynamic(light: (1, 0.9412, 0.9412, 1), dark: (0.9412, 0.2706, 0.2431, 0.14))
    public static let dangerText = Color.rdlDynamic(light: (0.8, 0.1843, 0.1608, 1), dark: (1, 0.6039, 0.6039, 1))
    public static let warning = Color.rdlDynamic(light: (0.9608, 0.6549, 0.0431, 1), dark: (1, 0.8235, 0.4, 1))
    public static let warningSoft = Color.rdlDynamic(light: (1, 0.9725, 0.902, 1), dark: (0.9608, 0.6549, 0.0431, 0.14))
    public static let warningText = Color.rdlDynamic(light: (0.5412, 0.3569, 0, 1), dark: (1, 0.8235, 0.4, 1))
    public static let info = Color.rdlDynamic(light: (0.1843, 0.4, 0.9647, 1), dark: (0.5176, 0.6627, 1, 1))
    public static let infoSoft = Color.rdlDynamic(light: (0.9333, 0.9569, 1, 1), dark: (0.1843, 0.4, 0.9647, 0.16))
    public static let scrim = Color.rdlDynamic(light: (0.0431, 0.0431, 0.051, 0.48), dark: (0, 0, 0, 0.64))
}

/// Accent pack. Pick one per product and inject with `.rdlAccent(.lime)`.
public struct RDLAccent {
    public let accent: Color, accentStrong: Color, accentSoft: Color, onAccent: Color, accentText: Color
    public static let lime = RDLAccent(accent: Color(rdlR: 0.7961, g: 0.9373, b: 0.2627, a: 1), accentStrong: Color(rdlR: 0.698, g: 0.851, b: 0.1647, a: 1), accentSoft: Color.rdlDynamic(light: (0.9333, 0.9843, 0.7686, 1), dark: (0.7961, 0.9373, 0.2627, 0.16)), onAccent: Color(rdlR: 0.0431, g: 0.0431, b: 0.051, a: 1), accentText: Color.rdlDynamic(light: (0.3725, 0.4784, 0.0314, 1), dark: (0.8471, 0.9608, 0.4353, 1)))
    public static let violet = RDLAccent(accent: Color(rdlR: 0.4431, g: 0.3216, b: 0.9608, a: 1), accentStrong: Color(rdlR: 0.3529, g: 0.2314, b: 0.8588, a: 1), accentSoft: Color.rdlDynamic(light: (0.9569, 0.9451, 1, 1), dark: (0.4431, 0.3216, 0.9608, 0.16)), onAccent: Color(rdlR: 1, g: 1, b: 1, a: 1), accentText: Color.rdlDynamic(light: (0.3529, 0.2314, 0.8588, 1), dark: (0.6902, 0.6118, 1, 1)))
    public static let orange = RDLAccent(accent: Color(rdlR: 0.9608, g: 0.3725, b: 0.1412, a: 1), accentStrong: Color(rdlR: 0.8235, g: 0.2824, b: 0.0706, a: 1), accentSoft: Color.rdlDynamic(light: (1, 0.9529, 0.9333, 1), dark: (0.9608, 0.3725, 0.1412, 0.16)), onAccent: Color(rdlR: 0.0431, g: 0.0431, b: 0.051, a: 1), accentText: Color.rdlDynamic(light: (0.8235, 0.2824, 0.0706, 1), dark: (1, 0.6157, 0.4588, 1)))
    public static let ocean = RDLAccent(accent: Color(rdlR: 0.1843, g: 0.4, b: 0.9647, a: 1), accentStrong: Color(rdlR: 0.1216, g: 0.3098, b: 0.8196, a: 1), accentSoft: Color.rdlDynamic(light: (0.9333, 0.9569, 1, 1), dark: (0.1843, 0.4, 0.9647, 0.16)), onAccent: Color(rdlR: 1, g: 1, b: 1, a: 1), accentText: Color.rdlDynamic(light: (0.1216, 0.3098, 0.8196, 1), dark: (0.5176, 0.6627, 1, 1)))
    public static let gold = RDLAccent(accent: Color(rdlR: 0.8667, g: 0.6824, b: 0.2275, a: 1), accentStrong: Color(rdlR: 0.7647, g: 0.5725, b: 0.1333, a: 1), accentSoft: Color.rdlDynamic(light: (0.9922, 0.9725, 0.9176, 1), dark: (0.8667, 0.6824, 0.2275, 0.16)), onAccent: Color(rdlR: 0.0431, g: 0.0431, b: 0.051, a: 1), accentText: Color.rdlDynamic(light: (0.4314, 0.3137, 0.0549, 1), dark: (0.9216, 0.7686, 0.3608, 1)))
}

private struct RDLAccentKey: EnvironmentKey { static let defaultValue = RDLAccent.lime }
public extension EnvironmentValues {
    var rdlAccent: RDLAccent { get { self[RDLAccentKey.self] } set { self[RDLAccentKey.self] = newValue } }
}
public extension View {
    func rdlAccent(_ accent: RDLAccent) -> some View { environment(\.rdlAccent, accent) }
}

// MARK: - Type

public struct RDLTextStyle {
    public let size: CGFloat, lineHeight: CGFloat, weight: Font.Weight, tracking: CGFloat
    public var font: Font { .system(size: size, weight: weight, design: .default) }
}
public enum RDLType {
    public static let displayXl = RDLTextStyle(size: 56, lineHeight: 60, weight: .medium, tracking: -1.96)
    public static let display = RDLTextStyle(size: 44, lineHeight: 48, weight: .medium, tracking: -1.32)
    public static let h1 = RDLTextStyle(size: 32, lineHeight: 38, weight: .semibold, tracking: -0.8)
    public static let h2 = RDLTextStyle(size: 26, lineHeight: 32, weight: .semibold, tracking: -0.52)
    public static let h3 = RDLTextStyle(size: 20, lineHeight: 26, weight: .semibold, tracking: -0.3)
    public static let title = RDLTextStyle(size: 17, lineHeight: 22, weight: .semibold, tracking: -0.17)
    public static let body = RDLTextStyle(size: 15, lineHeight: 22, weight: .regular, tracking: -0.07)
    public static let bodyStrong = RDLTextStyle(size: 15, lineHeight: 22, weight: .medium, tracking: -0.07)
    public static let label = RDLTextStyle(size: 14, lineHeight: 18, weight: .medium, tracking: -0.07)
    public static let caption = RDLTextStyle(size: 12, lineHeight: 16, weight: .medium, tracking: 0)
    public static let micro = RDLTextStyle(size: 11, lineHeight: 14, weight: .medium, tracking: 0.11)
}
public extension View {
    /// Applies an RDL type role: size, weight, tracking and line height.
    func rdlType(_ style: RDLTextStyle) -> some View {
        font(style.font)
            .tracking(style.tracking)
            .lineSpacing(max(0, style.lineHeight - style.size * 1.2))
    }
}

// MARK: - Space, radius, size, motion

public enum RDLSpace {
    public static let s0: CGFloat = 0
    public static let s1: CGFloat = 4
    public static let s2: CGFloat = 8
    public static let s3: CGFloat = 12
    public static let s4: CGFloat = 16
    public static let s5: CGFloat = 20
    public static let s6: CGFloat = 24
    public static let s7: CGFloat = 28
    public static let s8: CGFloat = 32
    public static let s10: CGFloat = 40
    public static let s12: CGFloat = 48
    public static let s14: CGFloat = 56
    public static let s16: CGFloat = 64
    public static let s20: CGFloat = 80
    public static let s0_5: CGFloat = 2
    public static let s1_5: CGFloat = 6
    public static let s2_5: CGFloat = 10
    public static let mobileGutter: CGFloat = 20
    public static let cardPadding: CGFloat = 20
    public static let cardGap: CGFloat = 12
    public static let sectionGap: CGFloat = 28
    public static let webSidebar: CGFloat = 248
    public static let webGutter: CGFloat = 32
    public static let webGridGap: CGFloat = 16
}
public enum RDLRadius {
    public static let xs: CGFloat = 6
    public static let sm: CGFloat = 10
    public static let md: CGFloat = 14
    public static let lg: CGFloat = 20
    public static let xl: CGFloat = 24
    public static let xxl: CGFloat = 28
    public static let xxxl: CGFloat = 32
    public static let pill: CGFloat = 999
}
public enum RDLSize {
    public static let controlSm: CGFloat = 36
    public static let controlMd: CGFloat = 44
    public static let controlLg: CGFloat = 56
    public static let iconButton: CGFloat = 44
    public static let tabBar: CGFloat = 64
    public static let avatarSm: CGFloat = 32
    public static let avatarMd: CGFloat = 40
    public static let avatarLg: CGFloat = 56
    public static let iconSm: CGFloat = 16
    public static let iconMd: CGFloat = 20
    public static let iconLg: CGFloat = 24
}
public enum RDLMotion {
    public static let fast: Double = 0.12
    public static let base: Double = 0.2
    public static let slow: Double = 0.32
    public static let chart: Double = 0.6
    public static let spring = Animation.spring(response: 0.35, dampingFraction: 0.82)
    public static let standard = Animation.timingCurve(0.2, 0, 0, 1, duration: 0.2)
    public static let stagger: Double = 0.04
}
